"""Assemble ai-workflow/sprint-1-verification.md from saved evidence and exports.

Run: python -m funnel.verification_sprint1

Reads evidence written by commands (dbt_build_runs.json, verify.json, smoke_production.txt,
screenshots.txt, pytest.txt), the JSON exports in web/public/data/, and git history, so that no
figure in the verification file is typed by hand.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Any

from funnel.common import DUCKDB_MEMORY_LIMIT, DUCKDB_THREADS, MIN_AVAILABLE_RAM_GB, REPO_ROOT, write_text
from funnel.export import CORRECTION_LOG, WEB_DATA, parse_correction_log

EVIDENCE = REPO_ROOT / "ai-workflow" / "evidence" / "sprint-1"
OUT = REPO_ROOT / "ai-workflow" / "sprint-1-verification.md"
# Sprint 1 commits: every commit after the last Sprint 0 commit.
SPRINT_0_LAST = "460398e"


def _json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _export(name: str) -> Any:
    return _json(WEB_DATA / name)


def money(x: float) -> str:
    return f"${x:,.2f}"


def pct(x: float, digits: int = 2) -> str:
    return f"{x * 100:.{digits}f}%"


def sprint_commits() -> list[tuple[str, str]]:
    out = subprocess.run(["git", "-C", str(REPO_ROOT), "log", "--reverse", "--format=%h%x09%s",
                          f"{SPRINT_0_LAST}..HEAD"], capture_output=True, text=True, check=True).stdout
    return [tuple(line.split("\t", 1)) for line in out.splitlines() if line.strip()]  # type: ignore[misc]


def pytest_summary(text: str) -> str:
    lines = [ln for ln in text.splitlines() if ln.strip()]
    summary = next((ln for ln in reversed(lines) if " passed" in ln or " failed" in ln), "no summary line found")
    exit_line = next((ln for ln in reversed(lines) if ln.startswith("pytest_exit_code=")), "pytest_exit_code=?")
    return f"{summary.strip()}  ({exit_line.strip()})"


def top_categories(rows: list[dict[str, Any]], n: int = 3) -> tuple[list[dict[str, Any]], float, dict[str, Any] | None]:
    ranked = sorted(rows, key=lambda r: r["carted_value_with_no_observed_purchase"], reverse=True)
    total = sum(r["carted_value_with_no_observed_purchase"] for r in rows)
    unknown = next((r for r in ranked if r["category"] == "unknown"), None)
    return ranked[:n], total, unknown


def render() -> str:
    runs = _json(EVIDENCE / "dbt_build_runs.json")["runs"]
    build = [r for r in runs if r["dbt_args"] == ["build"]][-1]
    verify = _json(EVIDENCE / "verify.json")
    smoke = (EVIDENCE / "smoke_production.txt").read_text(encoding="utf-8")
    screens = (EVIDENCE / "screenshots.txt").read_text(encoding="utf-8")
    pytest_text = (EVIDENCE / "pytest.txt").read_text(encoding="utf-8")
    url = re.search(r"Smoke test against (\S+)", smoke).group(1)
    smoke_line = re.search(r"^(\d+/\d+ checks passed)$", smoke, re.MULTILINE)
    screen_pass = len(re.findall(r"^PASS ", screens, re.MULTILINE))
    screen_fail = len(re.findall(r"^FAIL ", screens, re.MULTILINE))

    kpis = _export("kpis.json")
    m = kpis["month"]
    paths = _export("purchase_paths.json")["rows"]
    cat = _export("funnel_category.json")
    dq = _export("data_quality.json")["rows"]
    top, total_carted, unknown = top_categories(cat["category_top"])
    unknown_rank = 1 + sorted(cat["category_top"], key=lambda r: r["carted_value_with_no_observed_purchase"],
                              reverse=True).index(unknown) if unknown else None
    sensitivity = [r for r in dq if r["metric_group"] == "long_session_sensitivity"]
    quality = [r for r in dq if r["metric_group"] == "data_quality"]

    log = parse_correction_log(CORRECTION_LOG.read_text(encoding="utf-8"))
    sprint1_entries = [e for e in log["entries"] if e["phase"].startswith("Sprint 1")]
    patch_entries = [e for e in log["entries"] if e["phase"].startswith("v1.0.1")]

    cov = build["test_coverage"]
    done = build["dbt_done_counts"]
    checks = verify["checks"]

    def fmt_dq(r: dict[str, Any], v: float) -> str:
        if r["metric_key"].endswith(("_share", "_rate")):
            return pct(v)
        if r["metric_key"].endswith(("revenue_per_session", "average_order_value")):
            return money(v)
        return f"{v:,.0f}"

    lines = [
        "# Sprint 1 verification",
        "",
        "> Generated by `python -m funnel.verification_sprint1` from `ai-workflow/evidence/sprint-1/`, the JSON exports",
        "> in `web/public/data/`, and git history. Do not edit by hand.",
        "",
        "## Production",
        "",
        f"- Live site: {url}",
        f"- Smoke test against production: `{smoke_line.group(1) if smoke_line else 'no summary line'}`"
        " (`ai-workflow/evidence/sprint-1/smoke_production.txt`).",
        f"- 390 px screenshots, light and dark: {screen_pass} page-theme combinations pass, {screen_fail} fail"
        " (no page overflow, no clipped scroll box); WebP files in `ai-workflow/evidence/sprint-1/`.",
        "",
        "## Memory settings and the 2 GB override",
        "",
        f"`ai-workflow/sprint-1.md` Step 3 specifies a 4 GB DuckDB limit. The project owner overrode it: the pipeline"
        f" runs with `memory_limit = {DUCKDB_MEMORY_LIMIT}`, {DUCKDB_THREADS} DuckDB threads, insertion order off,"
        " spill to `data/duckdb_tmp`, and dbt threads 1 (`analysis/funnel/common.py`, `pipeline/profiles.yml`)."
        f" Reason: on this machine a 4 GB ceiling left too little headroom; available memory"
        f" (`\\Memory\\Available MBytes`) stood near or below the {MIN_AVAILABLE_RAM_GB:g} GB gate that every heavy"
        " run must pass, so a 4 GB limit could exceed the memory actually available. The sprint brief is left as"
        " written; the override is recorded here and in `ai-workflow/correction-log.md`.",
        "",
        "## dbt build (final, full, from a clean tree)",
        "",
        f"- Commit `{build['manifest']['git_commit_sha'][:7]}`, clean tree: {not build['manifest']['git_worktree_dirty']}.",
        f"- `{build['dbt_summary'][-1] if build['dbt_summary'] else 'no summary'}`",
        f"- Models built: {cov['models_built']}; tests run {cov['tests_run']} of {cov['tests_expected']} expected.",
        f"- Elapsed {build['elapsed_seconds']} s; peak spill {build['peak_spill_bytes']:,} bytes;"
        f" {build['available_ram_gb_before_run']} GB available before the run.",
        "",
        "## Independent verification (`python -m funnel.verify`)",
        "",
        f"All checks match: **{verify['all_match']}** ({sum(c['match'] for c in checks)} of {len(checks)};"
        f" counts and DECIMAL sums exactly, rates within {verify['rate_tolerance']}).",
        "",
        "| Check | Independent | Compared with | Match |",
        "|---|---|---|---|",
        *[f"| {c['check']} | {c['independent']} | {c['against']}: {c['compared']} | {c['match']} |" for c in checks],
        "",
        "## Tests",
        "",
        f"`{pytest_summary(pytest_text)}`",
        "",
        "## Headline KPIs (from kpis.json)",
        "",
        f"- Sessions: {m['sessions']:,}",
        f"- Orders: {m['orders']:,}",
        f"- Revenue (primary): {money(m['revenue'])}; repeat purchase events collapsed: {money(m['revenue_repeat_collapsed'])}",
        f"- Average order value: {money(m['average_order_value'])}",
        f"- Revenue per session: {money(m['revenue_per_session'])}",
        f"- Session purchase rate: {pct(m['session_purchase_rate'])} ({m['sessions_with_purchase']:,} of {m['sessions']:,})",
        f"- View-to-cart session rate: {pct(m['view_to_cart_session_rate'])}"
        f" ({m['viewing_sessions_with_cart']:,} of {m['sessions_with_view']:,})",
        f"- Cart-session purchase rate: {pct(m['cart_session_purchase_rate'])}"
        f" ({m['cart_sessions_with_carted_product_purchase']:,} of {m['sessions_with_cart']:,})",
        "",
        "Added in v1.0.1 (metrics.md Changes 2026-09-26, third entry):",
        "",
        f"- Sessions with an observed purchase of a product with an observed same-session cart event:"
        f" {m['sessions_with_purchase_of_carted_product']:,}"
        f" ({pct(m['sessions_with_purchase_of_carted_product'] / m['sessions_with_purchase'], 1)} of purchasing sessions)",
        f"- Sessions with observed purchases only of products with no observed same-session cart event:"
        f" {m['sessions_with_purchases_only_of_uncarted_products']:,}"
        f" ({pct(m['sessions_with_purchases_only_of_uncarted_products'] / m['sessions_with_purchase'], 1)})",
        f"- Sessions with an observed cart event and an observed purchase, none of a carted product:"
        f" {m['cart_sessions_with_purchase_of_no_carted_product']:,}"
        f" ({pct(m['cart_sessions_with_purchase_of_no_carted_product'] / m['sessions_with_cart'])} of"
        f" {m['sessions_with_cart']:,} sessions with an observed cart event; with the cart-session purchase numerator"
        f" and cart sessions with no observed purchase, the three sum to"
        f" {m['cart_sessions_with_carted_product_purchase'] + m['cart_sessions_with_no_observed_purchase'] + m['cart_sessions_with_purchase_of_no_carted_product']:,})",
        "",
        "Published claims and their evidence are in `ai-workflow/claim-ledger.md` (owner sign-off, H9, pending).",
        "",
        "## Purchase paths (from purchase_paths.json)",
        "",
        *[f"- {p['purchase_path']}: {pct(p['revenue_share'])} of revenue ({money(p['revenue'])},"
          f" {p['purchase_events']:,} purchase events)" for p in paths],
        "",
        "## Top three top-level categories by carted value with no observed purchase in the session",
        "",
        f"Total across all top-level categories, unknown included: {money(total_carted)}. Shares below use that total.",
        "",
        "| Rank | Category | Carted value with no observed purchase | Share | Carted pairs with no observed purchase | Category revenue |",
        "|---|---|---|---|---|---|",
        *[f"| {i} | {r['category']} | {money(r['carted_value_with_no_observed_purchase'])}"
          f" | {pct(r['carted_value_with_no_observed_purchase'] / total_carted, 1)}"
          f" | {r['carted_pairs_with_no_observed_purchase']:,} | {money(r['revenue'])} |" for i, r in enumerate(top, 1)],
        "",
        (f"Unknown-category context: the unknown category ranks {unknown_rank} with"
         f" {money(unknown['carted_value_with_no_observed_purchase'])}"
         f" ({pct(unknown['carted_value_with_no_observed_purchase'] / total_carted, 1)} of the total), and missing"
         f" category codes cover {pct(cat['unknown_shares']['unknown_category_event_share'], 1)} of events and"
         f" {pct(cat['unknown_shares']['unknown_category_revenue_share'], 1)} of revenue."
         if unknown else "No unknown category row."),
        "",
        "## Long-session sensitivity (from data_quality.json)",
        "",
        "| Metric | All valid sessions | Excluding sessions over 24 hours |",
        "|---|---|---|",
        *[f"| {r['metric_label'].replace(', long-session sensitivity', '')} | {fmt_dq(r, r['value'])}"
          f" | {fmt_dq(r, r['value_excluding_long_sessions'])} |" for r in sensitivity],
        "",
        "## Data-quality metrics (from data_quality.json)",
        "",
        "| Metric | Basis | Value | Sprint 0, raw rows |",
        "|---|---|---|---|",
        *[f"| {r['metric_label']} | {r['basis']} | {fmt_dq(r, r['value'])}"
          f" | {'—' if r['sprint0_raw_basis_value'] is None else fmt_dq(r, r['sprint0_raw_basis_value'])} |"
          for r in quality],
        "",
        f"## Correction log: {len(sprint1_entries)} Sprint 1 entries",
        "",
        *[f"- {e['phase']} · {e['title']} ({e['origin']}; {e['caught_by']})" for e in sprint1_entries],
        "",
        f"## Correction log: {len(patch_entries)} v1.0.1 entries",
        "",
        *[f"- {e['phase']} · {e['title']} ({e['origin']}; {e['caught_by']})" for e in patch_entries],
        "",
        "## Sprint 1 commits",
        "",
        *[f"- `{sha}` {subject}" for sha, subject in sprint_commits()],
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    write_text(OUT, render())
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
