"""Assemble ai-workflow/sprint-0-verification.md from saved evidence files.

Run: python -m funnel.verification

Reads evidence written by commands (preflight.txt, ingest.json, profile.json,
pytest.txt) so that no figure in the verification file is typed by hand.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from funnel.common import EVIDENCE_DIR, KAGGLE_URL, REPO_ROOT, write_text
from funnel.ingest import KAGGLE_LICENSE_FIELD, PUBLISHER_USAGE_STATEMENT

OUT = REPO_ROOT / "ai-workflow" / "sprint-0-verification.md"


def _load(name: str) -> Any:
    path = EVIDENCE_DIR / name
    text = path.read_text(encoding="utf-8")
    return json.loads(text) if name.endswith(".json") else text


def _pytest_summary(text: str) -> str:
    lines = [ln for ln in text.splitlines() if ln.strip()]
    summary = next((ln for ln in reversed(lines) if " passed" in ln or " failed" in ln), "no summary line found")
    exit_line = next((ln for ln in reversed(lines) if ln.startswith("pytest_exit_code=")), "pytest_exit_code=?")
    return f"{summary.strip()}  ({exit_line.strip()})"


def render(preflight: str, ingest: dict[str, Any], profile: dict[str, Any], pytest_text: str) -> str:
    raw, conv, checks = ingest["raw_file"], ingest["conversion"], ingest["checks"]
    d, pr, cb, su, oa, orc, tm, et = (
        profile["duplicates"], profile["price"], profile["category_brand"], profile["sessions_users"],
        profile["ordering_anomalies"], profile["order_reconstruction"], profile["time"], profile["event_types"],
    )
    anomaly_rows = [
        ("Exact duplicate rows (surplus)", d["exact_duplicate_rows"]["surplus_rows"]),
        ("Same session/product/type/time (surplus)", d["near_duplicates_session_product_type_time"]["surplus_rows"]),
        ("Same session/product/type within one second (surplus)",
         d["near_duplicates_session_product_type_same_second"]["surplus_rows"]),
        ("Events outside October 2019 UTC", tm["events_outside_october_2019_utc"]),
        ("Zero-price events", pr["zero_price_events"]),
        ("Negative-price events", pr["negative_price_events"]),
        ("Null-price events", pr["null_price_events"]),
        ("Products with more than one distinct price", pr["products_with_more_than_one_distinct_price"]),
        ("category_code null or empty (events)", cb["category_code"]["null_or_empty_count"]),
        ("brand null or empty (events)", cb["brand"]["null_or_empty_count"]),
        ("category_id with more than one category_code", cb["category_ids_mapping_to_more_than_one_category_code"]),
        ("Null user_session (events)", su["null_user_session_events"]),
        ("Sessions with more than one user_id", su["sessions_with_more_than_one_user_id"]),
        ("Sessions spanning more than 24 hours", su["sessions_spanning_more_than_24_hours"]),
        ("Purchases with no view of the product in the session",
         oa["purchase_events_with_no_view_of_product_in_session"]),
        ("Purchases with no cart of the product in the session",
         oa["purchase_events_with_no_cart_of_product_in_session"]),
        ("Cart events with no view at or before in the session", oa["cart_events_with_no_view_at_or_before_in_session"]),
        ("Sessions with more than one purchase event", orc["sessions_with_more_than_one_purchase_event"]),
        ("(session, product) pairs with repeated purchase events",
         orc["session_product_pairs_with_more_than_one_purchase_event"]),
    ]
    table = "\n".join(f"| {label} | {value} |" for label, value in anomaly_rows)
    levels = ", ".join(f"`{k}` {v}" for k, v in et["counts"].items())
    return f"""# Sprint 0 verification

> Generated by `python -m funnel.verification` from `ai-workflow/evidence/sprint-0/` (preflight.txt, ingest.json,
> profile.json, pytest.txt). Do not edit by hand.

## Preflight output

Captured by the preflight command (see the command block at the top of the capture). Token values are never printed.

```text
{preflight.strip()}
```

## License finding

- Kaggle license field: `{KAGGLE_LICENSE_FIELD}` (rights reserved).
- Publisher's statement, verbatim, from {KAGGLE_URL}:

  > {PUBLISHER_USAGE_STATEMENT}

- Sprint 0 stopped at this check as unclear. The project owner decided on 2026-09-24 to rely on the publisher's
  statement, publish aggregates and findings only, and carry both attribution links in the README and site footer.
  See `docs/data-source.md`.

## Ingest

- File: `{raw['name']}`, retrieved {raw['retrieved_at_utc']} from the Kaggle file only.
- Size: {raw['size_bytes']} bytes; Kaggle-listed size {raw['kaggle_listed_size_bytes']}; match: {checks['size_matches_kaggle_listing']}.
- SHA-256: `{raw['sha256']}`
- Download artifact: `{raw['download_artifact']}`, SHA-256 `{raw['download_artifact_sha256']}`
- Rows: newline count {conv['csv_rows_newline_count']}; DuckDB CSV {conv['csv_rows_duckdb']}; Parquet {conv['parquet_rows']};
  match: {checks['row_counts_match']}. Types preserved: {checks['types_preserved']}.

## Tests

`{_pytest_summary(pytest_text)}`

## Profile anomaly summary (from profile.json)

Event type levels observed, overall counts: {levels}.

| Check | Count |
|---|---|
{table}

The full profile and the "Decisions needed before metric definitions" list are in `docs/data-profile.md`.
"""


def main() -> None:
    text = render(_load("preflight.txt"), _load("ingest.json"), _load("profile.json"), _load("pytest.txt"))
    write_text(OUT, text)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
